name: Update corps scores
on:
  schedule:
    # Run every day during June-August, 11:30pm EDT & 12:00am PDT
    - cron: "30 3 * 6-8 *"
    - cron: "0 7 * 6-8 *"
  workflow_dispatch:
    inputs:
      force-graph-update:
        type: boolean
        description: Update the graphs even if the database isn't updated
        required: false
        default: false

jobs:
  update-scores:
    runs-on: ubuntu-latest
    outputs:
      is_updated: ${{ steps.run-script.outputs.is_updated }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'VinShepp/corps-scores'
          ssh-key: ${{ secrets.CORPS_SCORES_KEY }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - id: run-script
        run: |
          cd app/fdcigrapher

          pip install -r requirements.txt
          python inputScores.py

          if ! git diff --exit-code scores2023.db; then
            echo "Found some differences!"
            echo "is_updated=true" >> $GITHUB_OUTPUT
          else
            echo "Didn't find differences"
            echo "is_updated=false" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.run-script.outputs.is_updated == 'true' }}
        run: |
          # Setup bot commit credentials
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Commit updated DB
          git add app/fdcigrapher/scores2023.db
          git commit -m "Automatic update of scores2023.db"
          git push
      - uses: actions/upload-artifact@v3
        with:
          name: updated-graphs
          path: app/fdcigrapher/*.html

  update-graphs:
    needs: update-scores
    runs-on: ubuntu-latest
    if: ${{ needs.update-scores.outputs.is_updated == 'true' || github.event.inputs.force-graph-update == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: updated-graphs
          path: corps-scores
      - run: |
          # Setup bot commit credentials
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Commit updated graphs
          git add .
          git commit -m "Automatic update of corps scores graphs"
          git push
